env:
  es2021: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

parserOptions:
  ecmaVersion: 12
  sourceType: 'module'

plugins:
  - 'import'

rules:
  indent:
    - error
    - 2
    - 'SwitchCase': 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console:
    - off
  eqeqeq:
    - error
  curly:
    - error
  camelcase:
    - warn
  no-trailing-spaces:
    - error
  import/no-commonjs: 
    - 'error'
  import/no-amd: 'error'
  import/no-import-module-exports: 'error'
  no-var: 'error'
  prefer-const: 'error'
